### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by jdekarske** [ARISE-Initiative/robosuite#355]
The current numba dependency does not support Python 3.10:

```
  File "/tmp/easy_install-hl2uylwf/numba-0.53.1/setup.py", line 47, in _guard_py_ver
RuntimeError: Cannot install on Python version 3.10.6; only versions >=3.6,<3.10 are supported.
```

Using `"numba>=0.52.0",` and installing from source seems to work, but I haven't fully tested.

**Comment by jhejna** [comment]
Numba seems to now support python 3.10, so the above issue should be resolved. However, there are a few Typing name that were deprecated in Python 3.10, particularly those that moved from `collections` to `collections.abc`:
```
  File "[hidden]/robosuite/robosuite/models/arenas/multi_table_arena.py", line 6, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' ([hidden]/lib/python3.10/collections/__init__.py)
```
A simple find and replace in the code would likely fix this.

**Comment by minhnh** [comment]
I believe you missed one instance of this `Iterable` import issue in [`models/arenas/multi_table_arena.py`](https://github.com/ARISE-Initiative/robosuite/blob/de64fa5935f9f30ce01b36a3ef1a3242060b9cdb/robosuite/models/arenas/multi_table_arena.py#L1).

**Comment by yukezhu** [comment]
Thanks @minhnh. Do you mind submitting a PR to get this fixed?

**Comment by minhnh** [comment]
@yukezhu I submitted #402 as a fix.
